version: '3.7'
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: prisma-bug-mssql
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: MyStrongPassword!
    ports:
      - '1433:1433'

